name: Build APK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Permitir execução do Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Compilar APK Debug
        run: ./gradlew assembleDebug

      - name: Upload do APK como artefato
        uses: actions/upload-artifact@v3
        with:
          name: mafiamiojo-apk
          path: app/build/outputs/apk/debug/app-debug.apk
